### ISSUE TITLE
Error: nrow(x) == nrow(y) is not TRUE

### ISSUE THREAD

**Issue by tungmilan** [thomasp85/patchwork#3] opened 2017-12-07 06:51 UTC
Hello Thomas,

Thanks again for developing this. I got the above error message while doing this:

```
library(ggplot2)
library(patchwork)

cdf1 <- ggplot(mtcars, aes(x = mpg, color = factor(cyl))) +
  facet_grid(am ~ .) +
  stat_ecdf(geom = "step", size = 1.0) +
  theme(aspect.ratio = 1) +
  theme(legend.position = "bottom") + guides(col = guide_legend(nrow = 1)) 
cdf1

p1 <- ggplot(mpg, aes(displ, cty)) + 
  facet_grid(drv ~ cyl) +
  geom_point()
p1

p1 + cdf1 + plot_layout(ncol = 2, widths = c(3, 1))
```

Any idea what went wrong?

**Comment by thomasp85** [comment] 2017-12-07 08:58
I'll look into it - It is probably a matter of me not taking care of all edge cases when aligning the plotting areas to each other...

**Comment by tungmilan** [comment] 2017-12-07 16:48
That's my guess as well. It worked (not that pretty) after removing   

`
theme(legend.position = "bottom") + guides(col = guide_legend(nrow = 1)) 
`   

```
cdf1 <- ggplot(mtcars, aes(x = mpg, color = factor(cyl))) +
  facet_grid(am ~ .) +
  theme(aspect.ratio = 1) +
  stat_ecdf(geom = "step", size = 1.0) 
cdf1

p <- ggplot(mpg, aes(displ, cty)) + 
  facet_grid(drv ~ cyl) +
  geom_point()
p

p + cdf1 + plot_layout(ncol = 2, widths = c(4, 1))
```

![rplot03](https://user-images.githubusercontent.com/6590141/33726894-3ee5e33a-db2b-11e7-9265-240345b505b9.png)

**Comment by thomasp85** [comment] 2017-12-10 22:01
I'm quite sure this is me not taking care of other guide positions than 'right'. It will get fixed in due time

**Comment by thomasp85** [comment] 2017-12-10 22:04
Also, the weird sizing in the rightmost panel is due to fixed aspect ratio, which is being taken care of as well

**Closed** 2017-12-18 15:27 UTC

**Comment by tungmilan** [comment] 2017-12-18 17:12
Thanks for the fix @thomasp85 ! Is it possible to fix the legend position? Right now it's hanging alone in the right corner (see figure)

![rplot](https://user-images.githubusercontent.com/6590141/34118406-83aada7e-e3d3-11e7-9dfc-e6a36e3afb11.png)

**Comment by thomasp85** [comment] 2017-12-18 17:40
It is by design that guides are kept aligned across plots, so that is not going to change - I will however add a feature that lets you collect all guides in a shared area

**Comment by tungmilan** [comment] 2017-12-18 18:24
Thanks! Would be great to have something similar to `egg` or `cowplot` packages   

1. `egg`   

```egg::ggarrange(p1, cdf1, ncol = 2, widths = c(2, 1))```

![rplot03](https://user-images.githubusercontent.com/6590141/34121210-1aac46ac-e3dd-11e7-9a48-4ddf9509b182.png)

2. `cowplot`  

```cowplot::plot_grid(p1, cdf1, ncol = 2)```  

![rplot04](https://user-images.githubusercontent.com/6590141/34121293-58c2ca56-e3dd-11e7-838e-cd0ac7d52de7.png)

```
cowplot::plot_grid(p1, cdf1, ncol = 2,
                   align = "h", axis = "tb")
```

![rplot05](https://user-images.githubusercontent.com/6590141/34121335-812f014e-e3dd-11e7-9587-4a1577a401a1.png)

**Comment by thomasp85** [comment] 2017-12-18 21:25
Well, 1 and 3 is already supported as it is basically just removing your aspect ratio setting in the right plot (so to get it in `patchwork` you simply don't specify it). Number 2 is not going to happen as the whole goal of patchwork is seamlessly aligning plots. Number 4 is closest to what I do except it opts to keep the legend together with the axis. I don't particularly like that look either and it would get even worse if plot 1 had a legend as well...
