### ISSUE TITLE
Extraneous positioning dataframe emitted when combining grobs in Rmarkdown notebooks

### ISSUE THREAD

**Issue by davidski** [thomasp85/patchwork#231] opened 2021-01-08 20:04 UTC
As always, thank you so much for the wonderful packages!

Under patchwork 1.1.1 (sessioninfo here: [sessioninfo.txt](https://github.com/thomasp85/patchwork/files/5789137/sessioninfo.txt)), all the grob combination operations I can think of (`+`, `/`, `wrap_plots()`, etc). print the positioning frame when run in the context of a RMarkdown notebook. This dataframe is not output when run from the console.

The constructed patchwork object otherwise works as expected, so this is a display issue when generating notebooks rather than a critical functionality issue.

Issue has been replicated via the R4DS Slack community as well.

```r
library(ggplot2)
library(patchwork)
gg1 <- ggplot(mtcars, aes(mpg, cyl)) + 
  geom_point()

gg2 <- ggplot(mtcars, aes(hp, disp)) + 
  geom_point()

foo <- gg1 + gg2 + plot_layout(ncol = 1)
```
![Screen Shot 2021-01-08 at 11 26 45 AM](https://user-images.githubusercontent.com/2313762/104058537-bb14f300-51a8-11eb-8b4c-628461278503.png)

**Comment by vadimus202** [comment] 2021-01-19 14:43
I noticed the same issue after upgrading some tidyverse packages. The dat frame only prints during assignment of combined plots to a variable.

**Comment by rspreafico** [comment] 2021-02-01 12:14
Same here

**Comment by davidski** [comment] 2021-06-06 21:59
@thomasp85 Any chance you could give a pointer on where to look to debug this issue? I'm happy to give a stab and identifying the root problem but am having a bit of uphill climb on understanding the flow of what's involved in this issue. Any debug guide you could give would be super appreciated. I'd love to get this issue fixed!

**Comment by thomasp85** [comment] 2021-08-02 10:25
Hum... this looks super weird and I have no idea on top of my head for where the issue is

I'm sure I can fix this when I get around to it, but I'm afraid I wouldn't know how to guide others in the meantime

**Comment by kevinushey** [comment] 2023-08-08 16:33
I've taken a look, and it looks like a bug in RStudio. To explain the behavior:

1. When executing a Notebook chunk, RStudio inserts its own `print()` overrides, so that it can detect and capture attempts to print R objects. This is what allows RStudio to capture e.g. `data.frame` print-outs in a clean way.
2. RStudio also tries to detect changes to objects in the Environment pane as code chunks are executed. When new objects are created, or changed, we try to introspect those new objects to learn a bit more about those objects.
3. To that end, when inspecting the `foo` object, we call `str(foo)` -- but this involves calling `print()` when examining some of the internal data in `foo`.
4. Unfortunately, because the `print()` overrides in (1) are still active, we end up inadvertently capturing that output into the Notebook chunk.

I think we can fix this on the RStudio side by making sure we deactivate our print overrides when updating the Environment pane.

**Comment by thomasp85** [comment] 2023-08-11 10:28
Thanks @kevinushey — I'm going to close it here as there is nothing more to do on the patchwork side of things

**Closed by thomasp85** 2023-08-11 10:28 UTC
Labels: bug
