### ISSUE TITLE
Duplicate guides are not removed in wrap_plots()

### ISSUE THREAD

**Issue by benediktclaus** [thomasp85/patchwork#194] opened 2020-06-17 06:36 UTC
When combining multiple plots from a list with `wrap_plots()` and setting the argument to `guides = "collect"`, the guides are collected as expected, but duplicate guides aren't removed.

``` r
library(tidyverse)
library(patchwork)

p1 <- ggplot(mtcars, aes(x = mpg, y = wt, color = as_factor(cyl))) +
  geom_point()

p2 <- ggplot(mtcars, aes(x = mpg, y = wt, color = as_factor(cyl))) +
  geom_point()

p3 <- ggplot(mtcars, aes(x = mpg, y = wt, color = as_factor(cyl))) +
  geom_point()

plot_list <- list(p1, p2, p3)

wrap_plots(plot_list, guides = "collect")
```

![](https://i.imgur.com/3Wxd5a6.png)

<sup>Created on 2020-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment] 2020-06-17 06:41
Duplicate of #170 - already fixed in master

**Closed by thomasp85** 2020-06-17 06:41 UTC
