### ISSUE TITLE
Feature request: add tableGrob() objects

### ISSUE THREAD

**Issue by LineStaunstrup** [thomasp85/patchwork#24] opened 2018-01-15 15:41 UTC
Hi Thomas,

Thank you for a nice package that is build up in a very intuitive way. A feature I am missing though is the possibility to add tables as well as plots. I know you can do this with grid.arrange(), and I really miss that feature. 

/Line

**Comment by thomasp85** [comment] 2018-01-22 09:41
Duplicate of #13 

I'm planning to add a `wrap_grob()` function that would allow adding arbitrary grob objects

**Closed** 2018-01-25 14:15 UTC
